<servers>
<server name="1.Server Siji" ca="0" continent_code="ID" country="No.1: Umum 1" country_code="ID" ip="144.76.73.12" port="42466" region="Server 1" url="http://mumble-de.cleanvoice.com"/>
<server name="2.Server Loro" ca="0" continent_code="ID" country="No.2: Umum 2" country_code="ID" ip="144.76.73.12" port="42464" region="Server 2" url="http://mumble-de.cleanvoice.com"/>
</servers>

